import Head from 'next/head'
import NavBar from '../Components/NavBar'
import HomePage from './PageContainer/Home'
import Banner from './PageContainer/Banner'
import Slide from './PageContainer/Slide'
import Roadmap from './PageContainer/Roadmap'
import Team from './PageContainer/Team'
import Contact from './PageContainer/Contact'
import Footer from './PageContainer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HomePage />
      <Banner />
      <Slide />
      <Roadmap />
      <Team />
      <Contact />
      <Footer />
    </>
  )
}
